return {
    "Blue Lightsaber.png",
    "Brazil.png",
    "Chrome.png",
    "Donald Trump.png",
    "Energy Sword.png",
    "France.png",
    "Germany.png",
    "Green Lightsaber.png",
    "Iran.png",
    "Japan.png",
    "Minecraft Diamond Axe.png",
    "Minecraft Diamond Hoe.png",
    "Minecraft Diamond Pickaxe.png",
    "Minecraft Diamond Sword.png",
    "Multi Cursors.png",
    "Poland.png",
    "Portugal.png",
    "Runescape.png",
    "Russia.png",
    "Sonic.png",
    "Spain.png",
    "USA.png",
    "United Kingdom.png",
    "Windows XP.png"
}
